**不建议使用QQ支付：您的银行卡暂不支持提现**
**不支持使用PayPal： 您必须年满18岁才能申请**
<img src="http://jiecs.xyz/sponsor_me/pay.jpg"/>

**使用加密货币**
http://www.jiecs.xyz/sponsor_me/cryptocurrency.html

**支付宝扫码红包**
打开支付宝首页搜*701445576*领红包，领到大红包的小伙伴赶紧使用哦！
<img src="http://jiecs.xyz/sponsor_me/QR_redpacket.jpg"  style="zoom: 15%;" />

**以下推广优惠链接**
**[阿里云--云产品提供商]**
https://www.aliyun.com/minisite/goods?userCode=xf5jvm3c
https://www.aliyun.com/1111/new?userCode=xf5jvm3c
https://www.aliyun.com/activity/daily/bestoffer?userCode=xf5jvm3c
https://www.aliyun.com/activity?userCode=xf5jvm3c
https://www.aliyun.com/daily-act/ecs/2020ecs_lottery?userCode=xf5jvm3c
https://www.aliyun.com/purchasing/2021?userCode=xf5jvm3c

**[腾讯云--云产品提供商]**
https://curl.qcloud.com/KLrZExcA
https://curl.qcloud.com/4vXP3NjT
https://curl.qcloud.com/uYAJtsus
https://curl.qcloud.com/Vr4rIR81
https://curl.qcloud.com/9k7jbu0y

**[宝塔--服务器运维面板]**
https://www.bt.cn/?invite_code=MV95b3poemQ=
